language: generic

branches:
    only:
        - master

before_deploy:
    - git config --local user.name "$github_user_name"
    - git config --local user.email "$github_user_email"
    - DATE_FORMATTED=$(date +'%Y-%m-%d')
    - export DATE_FORMATTED
    - git tag "Release-$DATE_FORMATTED"
    - bash ./.build-scripts/build-release.sh

deploy:
    provider: releases
    file: "dddgamer-softmod-pack.zip"
    name: "Release-$DATE_FORMATTED"
    api_key: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    skip_cleanup: true # Prevent travis from cleaning out the branch before the deploy occurs
    prerelease: true
    on:
        branch: master # Build only from master
